CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL,
    addressee_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendship UNIQUE (requester_user_id, addressee_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT,
    schedule_date DATE NOT NULL,
    title VARCHAR(200) NOT NULL,
    start_time TIME,
    end_time TIME,
    description VARCHAR(1000),
    shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS owner_user_id BIGINT;
ALTER TABLE schedule_item ADD COLUMN IF NOT EXISTS shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_user_username ON app_user(username);
CREATE INDEX IF NOT EXISTS idx_friendship_requester ON friendship(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_addressee ON friendship(addressee_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_date ON schedule_item(owner_user_id, schedule_date);
