CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    email VARCHAR(254),
    total_points INTEGER NOT NULL DEFAULT 0,
    display_name VARCHAR(100) NOT NULL,
    profile_bio VARCHAR(500),
    x_url VARCHAR(1000),
    stream_url VARCHAR(1000),
    profile_image_url VARCHAR(1000),
    profile_icon_color VARCHAR(7),
    profile_image_data BYTEA,
    profile_image_content_type VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL REFERENCES app_user(id),
    addressee_user_id BIGINT NOT NULL REFERENCES app_user(id),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friendship UNIQUE (requester_user_id, addressee_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT REFERENCES app_user(id),
    schedule_date DATE NOT NULL,
    priority VARCHAR(10) NOT NULL DEFAULT 'LOW',
    device_type VARCHAR(30) NOT NULL DEFAULT 'PC',
    rank_band VARCHAR(100),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    message_shareable BOOLEAN NOT NULL DEFAULT FALSE,
    source_schedule_item_id BIGINT,
    source_owner_user_id BIGINT REFERENCES app_user(id),
    title VARCHAR(200) NOT NULL,
    start_time TIME,
    end_time TIME,
    description VARCHAR(1000),
    discord_invite_url VARCHAR(1000),
    shared_with_friends BOOLEAN NOT NULL DEFAULT FALSE,
    joinable BOOLEAN NOT NULL DEFAULT FALSE,
    recruitment_limit INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedule_source_schedule
        FOREIGN KEY (source_schedule_item_id) REFERENCES schedule_item(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS schedule_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    participant_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_participant UNIQUE (schedule_item_id, participant_user_id)
);

CREATE TABLE IF NOT EXISTS schedule_join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    requester_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    comment VARCHAR(500) NOT NULL,
    game_id VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_join_request UNIQUE (schedule_item_id, requester_user_id)
);

CREATE TABLE IF NOT EXISTS point_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    action_type VARCHAR(50) NOT NULL,
    action_label VARCHAR(200) NOT NULL,
    points INTEGER NOT NULL,
    action_key VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_point_history_user_action_key UNIQUE (user_id, action_key)
);

CREATE TABLE IF NOT EXISTS schedule_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    action_type VARCHAR(30) NOT NULL,
    action_detail VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES app_user(id),
    game_title VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL REFERENCES board_thread(id) ON DELETE CASCADE,
    author_user_id BIGINT NOT NULL REFERENCES app_user(id),
    body VARCHAR(1000) NOT NULL,
    schedule_date DATE,
    start_time TIME,
    rank_band VARCHAR(100),
    recruitment_limit INTEGER,
    discord_invite_url VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post_interest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES board_post(id) ON DELETE CASCADE,
    requester_user_id BIGINT NOT NULL REFERENCES app_user(id),
    comment VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS board_post_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES board_post(id) ON DELETE CASCADE,
    participant_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_board_post_participant UNIQUE (post_id, participant_user_id)
);

CREATE TABLE IF NOT EXISTS board_post_join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES board_post(id) ON DELETE CASCADE,
    requester_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    comment VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_board_post_join_request UNIQUE (post_id, requester_user_id)
);

CREATE TABLE IF NOT EXISTS notification_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    actor_user_id BIGINT REFERENCES app_user(id) ON DELETE SET NULL,
    event_type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    endpoint VARCHAR(2000) NOT NULL UNIQUE,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friend_notification_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    friend_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_friend_notification_preference UNIQUE (user_id, friend_user_id)
);

CREATE TABLE IF NOT EXISTS player_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id BIGINT NOT NULL REFERENCES app_user(id),
    target_user_id BIGINT NOT NULL REFERENCES app_user(id),
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT,
    category VARCHAR(40),
    note VARCHAR(500),
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dm_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    user_b_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dm_conversation_pair UNIQUE (user_a_id, user_b_id)
);

CREATE TABLE IF NOT EXISTS direct_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES dm_conversation(id) ON DELETE SET NULL,
    sender_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    recipient_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    body VARCHAR(1000) NOT NULL,
    related_schedule_item_id BIGINT REFERENCES schedule_item(id) ON DELETE SET NULL,
    attachment_data BYTEA,
    attachment_content_type VARCHAR(120),
    attachment_file_name VARCHAR(300),
    attachment_size BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS label_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    label_key VARCHAR(50) NOT NULL,
    color_hex VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_label_colors_user_key UNIQUE (user_id, label_key)
);

CREATE TABLE IF NOT EXISTS todo_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todo_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL REFERENCES todo_item(id) ON DELETE CASCADE,
    action_type VARCHAR(30) NOT NULL,
    action_detail VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_username ON app_user(username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_friendship_requester ON friendship(requester_user_id);
CREATE INDEX IF NOT EXISTS idx_friendship_addressee ON friendship(addressee_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_date ON schedule_item(owner_user_id, schedule_date);
CREATE INDEX IF NOT EXISTS idx_schedule_owner_completed ON schedule_item(owner_user_id, completed);
CREATE INDEX IF NOT EXISTS idx_schedule_source_schedule ON schedule_item(source_schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_schedule ON schedule_participant(schedule_item_id);
CREATE INDEX IF NOT EXISTS idx_schedule_participant_user ON schedule_participant(participant_user_id);
CREATE INDEX IF NOT EXISTS idx_schedule_join_request_schedule ON schedule_join_request(schedule_item_id, status);
CREATE INDEX IF NOT EXISTS idx_schedule_join_request_requester ON schedule_join_request(requester_user_id, status);
CREATE INDEX IF NOT EXISTS idx_point_history_user_created_at ON point_history(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_schedule_history_schedule_id ON schedule_history(schedule_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_board_thread_game_title ON board_thread(game_title);
CREATE INDEX IF NOT EXISTS idx_board_post_thread_created_at ON board_post(thread_id, created_at);
CREATE INDEX IF NOT EXISTS idx_board_post_interest_post_created_at ON board_post_interest(post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_board_post_participant_post ON board_post_participant(post_id);
CREATE INDEX IF NOT EXISTS idx_board_post_participant_user ON board_post_participant(participant_user_id);
CREATE INDEX IF NOT EXISTS idx_board_post_join_request_post_status ON board_post_join_request(post_id, status);
CREATE INDEX IF NOT EXISTS idx_board_post_join_request_requester_status ON board_post_join_request(requester_user_id, status);
CREATE INDEX IF NOT EXISTS idx_notification_event_recipient_id ON notification_event(recipient_user_id, id);
CREATE INDEX IF NOT EXISTS idx_push_subscription_user_id ON push_subscription(user_id);
CREATE INDEX IF NOT EXISTS idx_player_report_status_created_at ON player_report(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_direct_message_conversation_created_at ON direct_message(conversation_id, created_at, id);
CREATE INDEX IF NOT EXISTS idx_direct_message_recipient_is_read ON direct_message(recipient_user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_direct_message_sender_created_at ON direct_message(sender_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_dm_conversation_user_a ON dm_conversation(user_a_id);
CREATE INDEX IF NOT EXISTS idx_dm_conversation_user_b ON dm_conversation(user_b_id);
CREATE INDEX IF NOT EXISTS idx_label_colors_user_id ON label_colors(user_id);
