ALTER TABLE board_post
    ADD COLUMN IF NOT EXISTS discord_invite_url VARCHAR(1000);

CREATE TABLE IF NOT EXISTS board_post_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES board_post(id) ON DELETE CASCADE,
    participant_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_board_post_participant UNIQUE (post_id, participant_user_id)
);

CREATE TABLE IF NOT EXISTS board_post_join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES board_post(id) ON DELETE CASCADE,
    requester_user_id BIGINT NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    comment VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_board_post_join_request UNIQUE (post_id, requester_user_id)
);

CREATE INDEX IF NOT EXISTS idx_board_post_participant_post ON board_post_participant(post_id);
CREATE INDEX IF NOT EXISTS idx_board_post_participant_user ON board_post_participant(participant_user_id);
CREATE INDEX IF NOT EXISTS idx_board_post_join_request_post_status ON board_post_join_request(post_id, status);
CREATE INDEX IF NOT EXISTS idx_board_post_join_request_requester_status ON board_post_join_request(requester_user_id, status);
