CREATE TABLE IF NOT EXISTS schedule_manual_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_item_id BIGINT NOT NULL REFERENCES schedule_item(id) ON DELETE CASCADE,
    participant_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_manual_participant UNIQUE (schedule_item_id, participant_name)
);

CREATE INDEX IF NOT EXISTS idx_schedule_manual_participant_schedule
    ON schedule_manual_participant(schedule_item_id);
